export const APP_COMMON_BASE ="APP_COMMON";

export const AppCommon = {
    APP_COMMON_REDIRECT_REQUESTED: `${APP_COMMON_BASE}_REDIRECT_REQUESTED`,
    APP_COMMON_REDIRECTED: `${APP_COMMON_BASE}_REDIRECTED`,
}

