export const LOGIN_BASE = "LOGIN";
export const REGISTER_BASE="REGISTER";

export const Auth = {
    LOGIN_STARTED: `${LOGIN_BASE}_STARTED`,
    LOGIN_SUCCEEDED:  `${LOGIN_BASE}_SUCCEEDED`,
    LOGIN_FAILED: `${LOGIN_BASE}_FAILED`,
    REGISTER_STARTED: `${REGISTER_BASE}_STARTED`,
    REGISTER_SUCCEEDED: `${REGISTER_BASE}_SUCCEEDED`,
    REGISTER_FAILED: `${REGISTER_BASE}_FAILED`
}
