export const LOGIN_BASE = "LOGIN";
export const REGISTER_BASE="REGISTER";
export const AUTHENTICATION_BASE= "AUTHENTICATION";

export const Auth = {
    LOGIN_STARTED: `${LOGIN_BASE}_STARTED`,
    LOGIN_SUCCEEDED:  `${LOGIN_BASE}_SUCCEEDED`,
    LOGIN_FAILED: `${LOGIN_BASE}_FAILED`,
    REGISTER_STARTED: `${REGISTER_BASE}_STARTED`,
    REGISTER_SUCCEEDED: `${REGISTER_BASE}_SUCCEEDED`,
    REGISTER_FAILED: `${REGISTER_BASE}_FAILED`,
    AUTHENTICATION_STARTED: `${AUTHENTICATION_BASE}_STARTED`,
    AUTHENTICATION_SUCCEEDED: `${AUTHENTICATION_BASE}_SUCCEEDED`,
    AUTHENTICATION_FAILED: `${AUTHENTICATION_BASE}_FAILED`,
    AUTHENTICATION_SIGNEDOUT: `${AUTHENTICATION_BASE}_SIGNEDOUT`
}

