export const PROFILE_BASE = "PROFILE";
export const USERINFO_BASE = "USERINFO";

export const Profile = {
    PROFILE_FETCH_STARTED: `${PROFILE_BASE}_STARTED`,
    PROFILE_FETCH_SUCCEEDED: `${PROFILE_BASE}_SUCCEEDED`,
    PROFILE_FETCH_FAILED: `${PROFILE_BASE}_FAILED`,
    USERINFO_FETCH_STARTED: `${USERINFO_BASE}_STARTED`,
    USERINFO_FETCH_SUCCEEDED: `${USERINFO_BASE}_SUCCEEDED`,
    USERINFO_FETCH_FAILED: `${USERINFO_BASE}_FAILED`
};